Added Contact retrieving
pakondratyuk/tinkoff-bot pull request #3
Opened 2017-03-28 15:03 UTC by VecnaSecrets

2017-03-28 18:25 UTC, pakondratyuk commented on src/main/scala/com/bankbot/TelegramUpdater.scala
> +                SessionManager.contacts = SessionManager.contacts ++ update.message.contact
тут должно отправляться сообщение актору sessionManager с новым контактом, а он уже будет его добавлять

2017-03-28 18:25 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +  var contacts: List[Contact] = List()
Список Контактов должен находится внутри актора, а не объекта. (у нас не должно быть sharebale mutable сущностей)

2017-03-28 18:25 UTC, pakondratyuk commented on src/main/scala/com/bankbot/NoSessionActions.scala
> +    case Contact(message: Message) => {
Не стоит делать отдельного case Contact
Пусть будет case Balance 
и обрабатываться он должен в SessionManager
В нем, ты проверишь есть ли уже этот контакт и если нет - отправишь кнопку пошарить

2017-03-28 18:25 UTC, pakondratyuk commented on src/main/scala/com/bankbot/TelegramUpdater.scala
> +                  noSessionActions ! NoSessionActions.Contact(update.message)
Должно быть
sessionManager ! SessionManager.Balance(update.message)

2017-04-06 08:19 UTC, pavelkondratyuk requested changes

2017-04-06 08:19 UTC, pakondratyuk commented on src/main/scala/com/bankbot/telegram/TelegramTypes.scala
> +  case class Contact(phone_number: String, first_name: String, last_name: String, user_id: Int)
last_name и user_id - должны быть в Option
https://core.telegram.org/bots/api#contact
Пройдись плз по всем case классам Телеграмма и проверь, чтобы опциональные поля были в Option

2017-04-06 08:19 UTC, pakondratyuk commented on src/main/scala/com/bankbot/TelegramUpdater.scala
> +        if (update.message.contact.nonEmpty) {
Тут нужен pattern matching
update.message.contact match {
case Some(contact) =>  ...
}

2017-04-06 08:19 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +  var contacts: Map[User, Contact] = Map()
contacts: Map[User, Contact] - должен быть внутри класса SessionManager
У тебя не должно быть доступа к нему из TelegramUpdater.
Я писал об этом в прошлом ревью

2017-04-06 19:54 UTC, pavelkondratyuk reviewed
И жду тестов)

2017-04-06 19:54 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +        self ! message
Сюда надо просто поместить часть из case Message
match message {
 case Message(_, _, ..., Some(contact)) => {
contacts += (from.get.id -> contact.get)
 val send = Map("chat_id" -> chat.id.toString,
 "text" -> "Thanks for sharing your contact!", "parse_mode" -> "HTML")
 telegramApi.sendMessage(send)
}
case _ => //Error
}

2017-04-06 19:54 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(message_id: Int, from: Option[User], chat: Chat, date: Int, text: Option[String], contact: Option[Contact]) => {
А это убрать)

2017-04-07 08:58 UTC, sergeypopov83 commented on src/main/scala/com/bankbot/telegram/TelegramTypes.scala
> +  case class User(id: Int, first_name: String, last_name: String, username: Option[String])
тесты не компилируются из-за изменения формата .
Делать ПР который не компилируются и при этом его могут смержить -  плохая идея

2017-04-07 11:26 UTC, sergeypopov83 commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(message_id: Int, from: User, chat: Chat, date: Int, text: Option[String], contact: Option[Contact]) => {
типы у полей можно не указывать, что бы не было так многословно...

2017-04-07 11:26 UTC, sergeypopov83 commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(message_id: Int, from: User, chat: Chat, date: Int, text: Option[String], contact: Option[Contact]) => {
case можно переписать чуть по-другому
case Message(_, Some(from), chat, _, _, Some(contact)) if contacts.contains(from.id) =>
      val send = Map("chat_id" -> chat.id.toString,
        "text" -> "Already in the contact list", "parse_mode" -> "HTML")
      telegramApi.sendMessage(send)
    case Message(_, Some(from), chat, _, _, Some(contact)) =>
      contacts += (from.id -> contact)
      val send = Map("chat_id" -> chat.id.toString,
        "text" -> "Thanks for sharing your contact!", "parse_mode" -> "HTML")
      telegramApi.sendMessage(send)

Так у тебя во-первых  код читается лучше, во-вторых нет .get вызовов, которые очень опасны
в-третьих  нет повисших if без else
В других местах можно провезти такой же рефакторинг

2017-04-07 11:26 UTC, sergeypopov83 commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(message_id: Int, from: User, chat: Chat, date: Int, text: Option[String], _) => {
пустой case не нужен или удали его или наполни каким-то смыслом

2017-04-07 11:26 UTC, sergeypopov83 commented on src/main/scala/com/bankbot/TelegramUpdater.scala
>    def receive = {
седлайте offset приватным, давайте соблюдать инкапсуляцию)
никакого shared mutable state

2017-04-07 22:29 UTC, pavelkondratyuk requested changes

2017-04-07 22:29 UTC, pakondratyuk commented on src/main/scala/com/bankbot/TelegramUpdater.scala
> +          case None =>
это не нужно

2017-04-07 22:29 UTC, pakondratyuk commented on src/test/scala/com/bankbot/TelegramUpdaterTest.scala
> +    "on /balance with " in {
Если это тест, на обработку сообщения с контактом, то тебе вообще не нужен в нем текст с командой(/balance)
И описание тести примерно такое:
"send PossibleContact message to SessionManager when update contains contact"

2017-04-07 22:29 UTC, pakondratyuk commented on src/test/scala/com/bankbot/TelegramUpdaterTest.scala
> +      val balanceMessage = Message(1, Some(testUser), testChat, 123, Some("/balance"), Some(testContact))
Соответственно вместо Some("balance") - None

2017-04-07 22:29 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(_, Some(from), chat, _, _, Some(contact)) if contacts.contains(from.id) => {
От этого надо избавиться и перенести функционал в case PossibleContact

2017-04-07 22:29 UTC, pakondratyuk commented on src/main/scala/com/bankbot/SessionManager.scala
> +    case Message(_, Some(from), chat, _, _, Some(contact)) => {
От этого надо избавиться и перенести функционал в case PossibleContact

2017-04-08 19:26 UTC, pavelkondratyuk approved these changes
Тест на добавление в contacts, добавим в следующем ПР

2017-04-08 19:27 UTC, merged